# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DB.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import yaml
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector as msql
db = yaml.load(open('db.yaml'))
user=db['user']
password=db['password']
con=msql.connect(host="localhost",user=user,passwd=password,database="healthapp")




class Ui_Saved(object):
    def setupUi(self, Saved):
        Saved.setObjectName("Saved")
        Saved.resize(973, 550)
        Saved.setStyleSheet("background-color: #2C3336;\n"
"font: 63 12pt \"Nunito\";")
        self.DatabaseBrowser = QtWidgets.QTextBrowser(Saved)
        self.DatabaseBrowser.setGeometry(QtCore.QRect(70, 130, 871, 361))
        self.DatabaseBrowser.setStyleSheet("background-color: white;\n"
"border-radius: 10px;")
        self.DatabaseBrowser.setObjectName("DatabaseBrowser")
        self.heading = QtWidgets.QLabel(Saved)
        self.heading.setGeometry(QtCore.QRect(420, 30, 181, 41))
        self.heading.setStyleSheet("color: cyan;\n"
"font: 81 24pt \"Nunito ExtraBold\";\n"
"")
        self.heading.setObjectName("heading")
        self.DatabaseRefresh = QtWidgets.QPushButton(Saved)
        self.DatabaseRefresh.setGeometry(QtCore.QRect(450, 500, 81, 31))
        self.DatabaseRefresh.setStyleSheet("border-radius:10px;\n"
"background-color: #3CB7A1;\n"
"color: white;")
        self.DatabaseRefresh.setObjectName("DatabaseRefresh")

        self.retranslateUi(Saved)
        QtCore.QMetaObject.connectSlotsByName(Saved)
        self.DatabaseRefresh.clicked.connect(self.getdb)
    def getdb(self):
        try:
            x=" "
            sql_select_Query = "select * from checking"
            cur = con.cursor()
            cur.execute(sql_select_Query)
            records = cur.fetchall()
            for row in records:
                x=x+"\n"+row[1]
            self.DatabaseBrowser.append(str(x))   
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Zero Input Error")
            msg.setInformativeText("An error occured")
            msg.setWindowTitle('Error')
            msg.exec_()
            
        
    def retranslateUi(self, Saved):
        _translate = QtCore.QCoreApplication.translate
        Saved.setWindowTitle(_translate("Saved", "Saved"))
        self.heading.setText(_translate("Saved", "Saved Data"))
        self.DatabaseRefresh.setText(_translate("Saved", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Saved = QtWidgets.QDialog()
    ui = Ui_Saved()
    ui.setupUi(Saved)
    Saved.show()
    sys.exit(app.exec_())
